---

- name: "Install text editor, terminal multiplexer and documentation"
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ basic_software_user_tools }}"


- name: "Install sysadmin and networking tools"
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ basic_software_sysadmin_tools }}"


- name: "Install python-related stuff"
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ basic_software_python_tools }}"